name: twitter_kit
description: Project to make it easier to access the Twitter API. Referring to the Twitter kit for Android.
version: 0.0.1
author: kitProject
homepage: https://github.com/kitProject-dev/twitter_kit_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  chopper: ^3.0.2
  oauth1: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.3.0
  chopper_generator: ^3.0.4

flutter:
  plugin:
    androidPackage: info.kitproject.twitter_kit
    pluginClass: TwitterKitPlugin
  assets:
    - assets/test/json/